### ISSUE TITLE
Major Points

### ISSUE THREAD

**Issue by kylecarlstrom** [TianZhiWang/cmput404-project#74]
- [ ] Server can host images #8, #20 @xinyi3 [Django Images](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ImageField)
- [ ] Connect to other nodes #42, #43, #44, #45 @TianZhiWang, @nettapper 
  - [ ] Add/delete local and remote friends #25, #27 
  - [x] Getting posts from other users #13, #19 
  - [x] Refactor API to be compliant @kylecarlstrom 
  - [x] Add pagination 
  - [x] Add tests @nettapper, @joshdeng 

@nettapper, @TianZhiWang, @joshdeng, @xinyi3 
Let's not leave this until the last moment like last time. Let's try to have this done by Thursday evening (March 23). Check the milestone for specifics [Milestone 2](https://github.com/TianZhiWang/cmput404-project)

**Comment by kylecarlstrom** [comment]
@nettapper, @xinyi3, @joshdeng, @TianZhiWang 
Hope you are all having a good weekend. Just a reminder that you should at least be thinking about how we are going to connect to other nodes. This is probably the hardest part of the project and we don't want to leave it until the last minute.

Try to start thinking about some of the issues that you foresee coming up. I think it makes sense to have a "Node" or "Host" model as it ties neatly with several of the server admin stories. However, we have to think about how authentication with other nodes will work. Should a node just be a mapping to a user, etc.

**Comment by kylecarlstrom** [comment]
- [ ] Posts are not encoded with source and origin upon creation
- [ ] We aren't handling the case when remote author unfriends our author. Need to check friendship.
